"""Pydantic schemas for API requests and responses."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    """Represents a tool call action."""
    tool_name: str = Field(..., description="Name of the tool to call")
    parameters: Dict[str, Any] = Field(..., description="Parameters for the tool call")
    reasoning: Optional[str] = Field(None, description="Reasoning for this tool call")


class ActionPlan(BaseModel):
    """Response schema for action plan generated by Gemini."""
    analysis: str = Field(..., description="Analysis of the spreadsheet data")
    recommended_actions: List[ToolCall] = Field(..., description="List of recommended tool calls")
    summary: str = Field(..., description="Summary of the action plan")
    priority: str = Field(..., description="Priority level: high, medium, or low")


class AnalysisRequest(BaseModel):
    """Request schema for spreadsheet analysis."""
    filename: str = Field(..., description="Name of the uploaded CSV file")
    prompt: Optional[str] = Field(None, description="Optional user prompt for analysis")


class AnalysisResponse(BaseModel):
    """Response schema for analysis endpoint."""
    action_plan: ActionPlan
    filename: str
    status: str
